apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-petclinic-aks
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 6  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petclinic-aks
  targetCPUUtilizationPercentage: 50
