---
# tasks file for apache-maven
- name: Vérifier si maven est déja installé
  stat: 
    path: '{{ maven_home_parent_directory }}/apache-maven-{{ maven_version }}'
  register: maven_installed

- name: télecharger les libs de maven
  get_url:
    url: '{{ maven_download_url }}'
    dest: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
  when: not maven_installed.stat.exists

- name: Unarchiver les libs maven
  unarchive:
    src: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
    dest: '{{ maven_home_parent_directory }}'
    copy: no
  when: not maven_installed.stat.exists

- name: supprimer l'ancien chemin de configuration
  file:
    path: /etc/profile.d/maven.sh
    state: absent

- name: Créer une nouveau fichier de configuration
  lineinfile:
    dest: /etc/profile.d/maven.sh
    line: '{{ item.line }}'
    create: yes
    state: present
  with_items:
    - { line: 'M2_HOME={{ maven_home_parent_directory }}/apache-maven-{{ maven_version }}' }
    - { line: 'PATH=$PATH:$M2_HOME/bin' }

- name: nettoyer le Home path
  file:
    state: absent
    path: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'

- name: importer les variables d'environement
  shell: 'source /etc/profile.d/maven.sh'

