jenkins_yum_package: jenkins
jenkins_yum_key_url: https://pkg.jenkins.io/redhat/jenkins.io.key
jenkins_yum_repo: http://pkg.jenkins.io/redhat-stable
jenkins_port: 8080
jenkins_user: samir
jenkins_pass: samir 
jenkins_fullname: samir
jenkins_email: samir.errikh@gmail.com
