---
- name: verifier l'ancien version de docker compose
  command: "{{ docker_compose_path }} --version"
  register: docker_compose_current_version
  check_mode: false
  changed_when: false
  failed_when: false

- name: supprimer l'ancienne version de docker-compose
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout

- name: Installer docker compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_path }}"
    mode: 0755
  when: >
    docker_compose_current_version.stdout is not defined
    or docker_compose_version not in docker_compose_current_version.stdout
