---
- name: verifier les anciens versions de docke s'ils sont installées
  package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: ajouter la GPG key.
  rpm_key:
    key: "{{ docker_yum_gpg_key }}"
    state: present

- name: ajouter le docker repository.
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    owner: root
    group: root
    mode: 0644

- name: Configure le  repo de docker nightly.
  ini_file:
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    section: 'docker-{{ docker_edition }}-nightly'
    option: enabled
    value: '{{ docker_yum_repo_enable_nightly }}'
    mode: 0644

- name: Configurer le repo de docker test.
  ini_file:
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    section: 'docker-{{ docker_edition }}-test'
    option: enabled
    value: '{{ docker_yum_repo_enable_test }}'
    mode: 0644

